language: cpp

compiler: 
- gcc
- clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install libglew-dev libwxgtk2.8-dev freeglut3-dev
  
before_script: cd src

script: 
- make logsim
- make runtests
- ./runtests
- make clean
- sed -i '/^#define USE_GUI/ s.^.//.' logsim.cc
- make logsim
- cd ../examples
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- ./test.sh
- cat test.txt
- cd errors
- ./error.sh
- cat error.txt
