language: cpp

compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y
  - sudo apt-get install libglew-dev libwxgtk2.8-dev freeglut3-dev
  
before_script: cd src

script: 
- make logsim
- make runtests
- ./runtests
- make clean
- sed -i '/^#define USE_GUI/ s.^.//.' logsim.cc
- make logsim
- cd ../examples
- ./test.sh
- cat text.txt
- cd errors
- ./errors.sh
- cat errors.txt
