#ifndef gui_id_h
#define gui_id_h

enum
{
	MY_SPINCNTRL_ID = wxID_HIGHEST + 1,
	MY_TEXTCTRL_ID,
	MY_BUTTON_ID,
	MENU_CLEAR_CIRCUIT,
	MENU_RELOAD_FILE,
	MENU_OPTIONS_EDIT,
	MENU_OPTIONS_RESET,
	MENU_OPTIONS_FASTERCR,
	MENU_OPTIONS_SLOWERCR,
	OUTPUT_TEXTCTRL_ID,
	SIMCTRL_BUTTON_RUN_ID,
	SIMCTRL_BUTTON_CONT_ID,
	SIMCTRL_BUTTON_RUNCONT_ID,
	MONITORS_ADD_BUTTON_ID,
	MONITORS_DEL_BUTTON_ID,
	SWITCHES_CTRL_ID,
	DEVICES_EDIT_BUTTON_ID,
	DEVICES_APPLY_BUTTON_ID,
	DEVICECREATE_BUTTON_ID,
	DEVICEDELETE_BUTTON_ID,
	DEVICES_ADDCONN_BUTTON_ID,
	DEVICES_DELCONN_BUTTON_ID,
	DEVICENAME_TEXTCTRL_ID,
	DEVICEOUTPUT_MONITOR_CB_ID,
	RUNSIM_TIMER_ID,
	OPTIONS_XSCALE_MIN_ID,
	OPTIONS_XSCALE_MAX_ID,
	OPTIONS_SIGHEIGHT_MIN_ID,
	OPTIONS_SIGHEIGHT_MAX_ID,
	OPTIONS_CONTRATE_ID,
	OPTIONS_DEBUG_MACHINECYCLES_ID,
	OPTIONS_DEBUG_SIMULATION_ID
};

#endif /* gui_id_h */
