#ifndef gui_id_h
#define gui_id_h

enum
{
	MY_SPINCNTRL_ID = wxID_HIGHEST + 1,
	MY_TEXTCTRL_ID,
	MY_BUTTON_ID,
	MENU_CLEAR_CIRCUIT,
	OUTPUT_TEXTCTRL_ID,
	SIMCTRL_BUTTON_RUN_ID,
	SIMCTRL_BUTTON_CONT_ID,
	MONITORS_ADD_BUTTON_ID,
	MONITORS_DEL_BUTTON_ID,
	SWITCHES_CTRL_ID,
	DEVICES_EDIT_BUTTON_ID,
	DEVICES_APPLY_BUTTON_ID,
	DEVICECREATE_BUTTON_ID,
	DEVICEDELETE_BUTTON_ID,
	DEVICES_ADDCONN_BUTTON_ID,
	DEVICES_DELCONN_BUTTON_ID,
	DEVICENAME_TEXTCTRL_ID,
	DEVICEOUTPUT_MONITOR_CB_ID
};

#endif /* gui_id_h */
